#!/bin/bash

if [[ $EUID -ne 0 && ! $SUID ]]; then
	printf "%s\n" "need root permissions"
	exit 1
fi

read -r -d '' sources << EOF
https://www.census.gov/geo/maps-data/data/docs/gazetteer/Gaz_counties_national.zip
https://www.census.gov/geo/maps-data/data/docs/gazetteer/Gaz_cousubs_national.zip
https://www.census.gov/geo/maps-data/data/docs/gazetteer/Gaz_places_national.zip
https://www.census.gov/geo/maps-data/data/docs/gazetteer/Gaz_zcta_national.zip
http://www.nws.noaa.gov/geodata/catalog/wsom/data/bp04de12.dbx
http://www.nws.noaa.gov/geodata/catalog/wsom/html/cntyzone.htm
http://weather.noaa.gov/data/nsd_cccc.txt
http://weather.noaa.gov/pub/data/zonecatalog.curr.tar
http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/dictionaries/metar.tbl
ftp://ftp.ncdc.noaa.gov/pub/data/inventories/COOP-ACT.TXT
EOF

for f in ${sources[@]}; do
	name="${f##*/}"
	[[ -f "$name" ]] || curl "$f" -o "/usr/share/weather/$name"
done
